apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: outpost-ha
spec:
  destinationCIDRs:
  - "172.18.0.0/16"
  selectors:
  - podSelector:
      matchLabels:
        org: alliance
  egressGroups:
    - nodeSelector:
        matchLabels:
          egress-gw: 'true'
      interface: net0
  # egressGroups:
  # - nodeSelector:
  #     matchLabels:
  #       kubernetes.io/hostname: kind-worker3
  #   egressIP: 172.18.0.42
  # - nodeSelector:
  #     matchLabels:
  #       kubernetes.io/hostname: kind-worker4
  #   egressIP: 172.18.0.43