---
apiVersion: v1
kind: Service
metadata:
  name: deathstar
  # labels:
  #   color: red
  # annotations:
  #   "lbipam.cilium.io/ips": "192.168.105.235"
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    org: empire
    class: deathstar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deathstar
spec:
  selector:
    matchLabels:
      org: empire
      class: deathstar
  replicas: 2
  template:
    metadata:
      labels:
        org: empire
        class: deathstar
        name: deathstar
    spec:
      containers:
        - name: deathstar
          image: docker.io/cilium/starwars
          imagePullPolicy: IfNotPresent