apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stateful-set
spec:
  serviceName: "mongodb-headless-service"
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        command:
          - "mongod"
          - "--replSet"
          - "rs0"
          - "--bind_ip_all"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo_root_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo_root_password
        - name: MONGO_REPLICA_SET_NAME
          value: "rs0"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
        volumeMounts:
              - name: mongodb-data
                mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      storageClassName: local-path 
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
